development:
 adapter: mysql2
 encoding: utf8
 database: sales_reports_dev
 pool: 5
 username: root #root
 password:

test:
 adapter: mysql2
 encoding: utf8
 database: sales_reports_test
 pool: 5
 username: root #root
 password:
